const sharp = require('sharp');
const path = require('path');
const fs = require('fs');

/**
 * Composites the Chemsroot logo onto an AI generated image.
 * @param {Buffer} generatedImageBuffer - The base image buffer generated by AI (e.g., DALL-E)
 * @returns {Promise<Buffer>} - The final image buffer with the logo overlay
 */
async function watermarkWithLogo(generatedImageBuffer) {
  const logoPath = path.join(__dirname, 'assets', 'logo.png');
  
  // Check if user has uploaded the logo
  if (!fs.existsSync(logoPath)) {
    console.warn("Logo not found at server/assets/logo.png. Returning original image.");
    return generatedImageBuffer;
  }

  try {
    // 1. Process the logo: resize it to be a sensible watermark size (e.g., width 250)
    // and make sure it has a transparent background.
    const processedLogo = await sharp(logoPath)
      .resize({ width: 300, fit: 'contain' })
      // Adding a subtle drop shadow/opacity could go here if needed
      .toBuffer();

    // 2. Composite the logo over the base image
    // We place it in the bottom right corner automatically.
    const watermarkedImage = await sharp(generatedImageBuffer)
      .composite([
        {
          input: processedLogo,
          gravity: 'southeast' // Bottom right
        }
      ])
      .toBuffer();

    return watermarkedImage;
  } catch (err) {
    console.error("Error applying logo watermark:", err);
    // Fallback to original image if compositing fails
    return generatedImageBuffer;
  }
}

module.exports = { watermarkWithLogo };
